### ISSUE TITLE
too many errors using IDE 2.3.3 and actual ESP-base

### ISSUE THREAD

**Issue by urs8000** [enwi/LED-Christmas-Tree#13]
In file included from e:\_development\Arduino\libraries\FastLED\src/FastLED.h:83,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\TreeEffects.h:4,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\config.h:9,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.h:8,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp:1:
e:\_development\Arduino\libraries\FastLED\src/fastspi.h:171:23: note: '#pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output'
  171 | #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp: In member function 'void Networking::stop()':
E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp:82:15: error: 'WIFI_SHUTDOWN' was not declared in this scope
   82 |     WiFi.mode(WIFI_SHUTDOWN, &savedState);
      |               ^~~~~~~~~~~~~
E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp: In member function 'void Networking::resume()':
E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp:91:15: error: 'WIFI_RESUME' was not declared in this scope
   91 |     WiFi.mode(WIFI_RESUME, &savedState);
      |               ^~~~~~~~~~~
E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp: In member function 'void Networking::getStatusJsonString(ArduinoJson::V720PB22::JsonObject&)':
E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp:121:60: warning: 'ArduinoJson::V720PB22::JsonObject ArduinoJson::V720PB22::JsonObject::createNestedObject(TChar*) [with TChar = const char]' is deprecated: use obj[key].to<JsonObject>() instead [-Wdeprecated-declarations]
  121 |     auto&& networking = output.createNestedObject("network");
      |                                                            ^
In file included from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:30,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.h:3,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp:1:
e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Object/JsonObject.hpp:210:14: note: declared here
  210 |   JsonObject createNestedObject(TChar* key) {
      |              ^~~~~~~~~~~~~~~~~~
E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp:127:69: warning: 'ArduinoJson::V720PB22::JsonObject ArduinoJson::V720PB22::JsonObject::createNestedObject(TChar*) [with TChar = const char]' is deprecated: use obj[key].to<JsonObject>() instead [-Wdeprecated-declarations]
  127 |     auto&& wifi_client = networking.createNestedObject("wifi_client");
      |                                                                     ^
In file included from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:30,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.h:3,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp:1:
e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Object/JsonObject.hpp:210:14: note: declared here
  210 |   JsonObject createNestedObject(TChar* key) {
      |              ^~~~~~~~~~~~~~~~~~
E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp:133:61: warning: 'ArduinoJson::V720PB22::JsonObject ArduinoJson::V720PB22::JsonObject::createNestedObject(TChar*) [with TChar = const char]' is deprecated: use obj[key].to<JsonObject>() instead [-Wdeprecated-declarations]
  133 |     auto&& wifi_ap = networking.createNestedObject("wifi_ap");
      |                                                             ^
In file included from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:30,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.h:3,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp:1:
e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Object/JsonObject.hpp:210:14: note: declared here
  210 |   JsonObject createNestedObject(TChar* key) {
      |              ^~~~~~~~~~~~~~~~~~
E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp: In member function 'void Networking::handleStatusApi(AsyncWebServerRequest*, TreeLight*)':
E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp:191:31: warning: 'DynamicJsonDocument' is deprecated: use JsonDocument instead [-Wdeprecated-declarations]
  191 |     DynamicJsonDocument output(3000);
      |                               ^
In file included from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:56,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.h:3,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp:1:
e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/compatibility.hpp:125:58: note: declared here
  125 | class ARDUINOJSON_DEPRECATED("use JsonDocument instead") DynamicJsonDocument
      |                                                          ^~~~~~~~~~~~~~~~~~~
E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp: In member function 'void Networking::handleConfigApiGet(AsyncWebServerRequest*)':
E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp:213:5: warning: 'template<unsigned int N> class ArduinoJson::V720PB22::StaticJsonDocument' is deprecated: use JsonDocument instead [-Wdeprecated-declarations]
  213 |     StaticJsonDocument<1024> document;
      |     ^~~~~~~~~~~~~~~~~~
In file included from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:56,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.h:3,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp:1:
e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/compatibility.hpp:63:58: note: declared here
   63 | class ARDUINOJSON_DEPRECATED("use JsonDocument instead") StaticJsonDocument
      |                                                          ^~~~~~~~~~~~~~~~~~
In file included from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Polyfills/type_traits.hpp:15,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Polyfills/utility.hpp:7,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Memory/MemoryPoolList.hpp:9,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Memory/ResourceManager.hpp:8,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Variant/JsonVariantConst.hpp:10,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Variant/VariantRefBase.hpp:9,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Array/ElementProxy.hpp:7,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Array/JsonArray.hpp:7,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:29,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.h:3,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp:1:
e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Polyfills/type_traits/is_convertible.hpp: In instantiation of 'const bool ArduinoJson::V720PB22::detail::is_convertible<IPAddress, long long int>::value':
e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Variant/VariantRefBase.hpp:301:30:   recursively required by substitution of 'template<class T> struct ArduinoJson::V720PB22::Converter<T, typename ArduinoJson::V720PB22::detail::enable_if<ArduinoJson::V720PB22::detail::is_enum<T>::value, void>::type> [with T = IPAddress]'
e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Variant/VariantRefBase.hpp:301:30:   required from 'bool ArduinoJson::V720PB22::detail::VariantRefBase<TDerived>::doSet(T&&) const [with TConverter = ArduinoJson::V720PB22::Converter<IPAddress, void>; T = const IPAddress&; TDerived = ArduinoJson::V720PB22::detail::MemberProxy<ArduinoJson::V720PB22::JsonObject, const char*>]'
e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Variant/VariantRefBase.hpp:80:44:   required from 'bool ArduinoJson::V720PB22::detail::VariantRefBase<TDerived>::set(const T&) const [with T = IPAddress; TDerived = ArduinoJson::V720PB22::detail::MemberProxy<ArduinoJson::V720PB22::JsonObject, const char*>]'
e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Object/MemberProxy.hpp:33:14:   required from 'ArduinoJson::V720PB22::detail::MemberProxy< <template-parameter-1-1>, <template-parameter-1-2> >& ArduinoJson::V720PB22::detail::MemberProxy< <template-parameter-1-1>, <template-parameter-1-2> >::operator=(const T&) [with T = IPAddress; TUpstream = ArduinoJson::V720PB22::JsonObject; TStringRef = const char*]'
E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp:129:38:   required from here
e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Polyfills/type_traits/is_convertible.hpp:33:41: error: conversion from 'IPAddress' to 'long long int' is ambiguous
   33 |   static const bool value = sizeof(probe(from_)) == sizeof(int);
      |                                   ~~~~~~^~~~~~~~
In file included from C:\Users\ursm\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\libraries\ESP8266WiFi\src/ESP8266WiFi.h:31,
                 from e:\_development\Arduino\libraries\ESP_Async_WebServer\src/ESPAsyncWebServer.h:38,
                 from e:\_development\Arduino\libraries\ESP_Async_WebServer\src/AsyncJson.h:48,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.h:4,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp:1:
C:\Users\ursm\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\cores\esp8266/IPAddress.h:80:9: note: candidate: 'IPAddress::operator uint32_t() const'
   80 |         operator uint32_t() const { return isV4()? v4(): (uint32_t)0; }
      |         ^~~~~~~~
C:\Users\ursm\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\cores\esp8266/IPAddress.h:81:9: note: candidate: 'IPAddress::operator uint32_t()'
   81 |         operator uint32_t()       { return isV4()? v4(): (uint32_t)0; }
      |         ^~~~~~~~
C:\Users\ursm\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\cores\esp8266/IPAddress.h:84:9: note: candidate: 'IPAddress::operator bool() const'
   84 |         operator bool () const { return isSet(); } // <-
      |         ^~~~~~~~
C:\Users\ursm\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\cores\esp8266/IPAddress.h:85:9: note: candidate: 'IPAddress::operator bool()'
   85 |         operator bool ()       { return isSet(); } // <- both are needed
      |         ^~~~~~~~
In file included from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Polyfills/type_traits.hpp:15,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Polyfills/utility.hpp:7,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Memory/MemoryPoolList.hpp:9,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Memory/ResourceManager.hpp:8,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Variant/JsonVariantConst.hpp:10,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Variant/VariantRefBase.hpp:9,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Array/ElementProxy.hpp:7,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Array/JsonArray.hpp:7,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:29,
                 from e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.h:3,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\Networking.cpp:1:
e:\_development\Arduino\libraries\ArduinoJson\src/ArduinoJson/Polyfills/type_traits/is_convertible.hpp:27:20: note:   initializing argument 1 of 'static int ArduinoJson::V720PB22::detail::is_convertible<From, To>::probe(To) [with From = IPAddress; To = long long int]'
   27 |   static int probe(To);
      |                    ^~
In file included from e:\_development\Arduino\libraries\FastLED\src/FastLED.h:83,
                 from E:\_development\Arduino\christmas tree lights\LED-Christmas-Tree\code\code.ino:7:
e:\_development\Arduino\libraries\FastLED\src/fastspi.h:171:23: note: '#pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output'
  171 | #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Multiple libraries were found for "DNSServer.h"
  Used: C:\Users\ursm\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2\libraries\DNSServer
  Not used: E:\_development\Arduino\libraries\DNSServer---esp32
exit status 1

Compilation error: 'WIFI_SHUTDOWN' was not declared in this scope

**Comment by enwi** [comment]
Did you follow these steps?
https://github.com/enwi/LED-Christmas-Tree/blob/main/software.md#compiling

**Comment by urs8000** [comment]
Make sure you have installed
my level
Version: 2.3.3    		Arduino IDE version 1.8.13 or newer
ESP8266 Boards (3.1.2)	ESP8266 Core exactly version 2.7.4 (background FastLED/FastLED#1322)
version=7.2.1			ArduinoJSON version 6.18.5 or newer
version=3.9.4			FastLED version 3.4.0 or newer
version=1.10.1		    AceButton version 1.9.1 or newer
version=1.2.2		    ESPAsyncTCP version 1.2.2 or newer
version=3.3.22		    ESPAsyncWebServer version 1.2.3 or newer

I'm using the most actual libraries and esp8266 level has nothing to do with compiling

networking library has changed and the code is on an old level
Networking.cpp:82:15: error: 'WIFI_SHUTDOWN' was not declared in this scope
Networking.cpp:91:15: error: 'WIFI_RESUME' was not declared in this scope
also config.cpp:209:23: warning: 'SPIFFS' is deprecated: SPIFFS has been deprecated should be adjusted
also class ARDUINOJSON_DEPRECATED

It would be useful if the last assigned setup was stored via "preferences" in eprom and used at next startup

**Comment by enwi** [comment]
> It would be useful if the last assigned setup was stored via "preferences" in eprom and used at next startup

It is

The code base is quite old now. So we will probably switch to platformio and fix those issues
